
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 'h\xccKdSm\xbd\xd8Q\xfb}\xb8\xe0\xcd\x10G'
    
_lr_action_items = {'BOLD':([0,4,5,6,7,8,9,16,23,],[3,3,3,3,3,3,3,25,3,]),'H2':([0,23,],[4,4,]),'H3':([0,23,],[5,5,]),'H1':([0,23,],[6,6,]),'H6':([0,23,],[7,7,]),'H4':([0,23,],[8,8,]),'H5':([0,23,],[9,9,]),'TEXT':([0,3,4,5,6,7,8,9,15,23,],[11,16,11,11,11,11,11,11,24,11,]),'HIGHLIGHT':([0,4,5,6,7,8,9,23,24,],[15,15,15,15,15,15,15,15,27,]),'CR':([2,10,11,12,13,14,17,18,19,20,21,22,25,26,27,],[-13,-12,-11,23,-10,-2,-5,-6,-4,-9,-7,-8,-14,-3,-15,]),'$end':([1,2,10,11,12,13,14,17,18,19,20,21,22,25,26,27,],[0,-13,-12,-11,-1,-10,-2,-5,-6,-4,-9,-7,-8,-14,-3,-15,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'body':([0,],[1,]),'HIGHLIGHTTEXT':([0,4,5,6,7,8,9,23,],[2,2,2,2,2,2,2,2,]),'BOLDTEXT':([0,4,5,6,7,8,9,23,],[10,10,10,10,10,10,10,10,]),'statement':([0,],[12,]),'factor':([0,4,5,6,7,8,9,23,],[13,17,18,19,20,21,22,13,]),'expression':([0,23,],[14,26,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> body","S'",1,None,None,None),
  ('body -> statement','body',1,'p_body','run.py',54),
  ('statement -> expression','statement',1,'p_state','run.py',59),
  ('statement -> statement CR expression','statement',3,'p_state','run.py',60),
  ('expression -> H1 factor','expression',2,'p_exp_cr','run.py',68),
  ('expression -> H2 factor','expression',2,'p_exp_cr','run.py',69),
  ('expression -> H3 factor','expression',2,'p_exp_cr','run.py',70),
  ('expression -> H4 factor','expression',2,'p_exp_cr','run.py',71),
  ('expression -> H5 factor','expression',2,'p_exp_cr','run.py',72),
  ('expression -> H6 factor','expression',2,'p_exp_cr','run.py',73),
  ('expression -> factor','expression',1,'p_exp_cr','run.py',74),
  ('factor -> TEXT','factor',1,'p_factor_text','run.py',93),
  ('factor -> BOLDTEXT','factor',1,'p_factor_text','run.py',94),
  ('factor -> HIGHLIGHTTEXT','factor',1,'p_factor_text','run.py',95),
  ('BOLDTEXT -> BOLD TEXT BOLD','BOLDTEXT',3,'p_bold_text','run.py',100),
  ('HIGHLIGHTTEXT -> HIGHLIGHT TEXT HIGHLIGHT','HIGHLIGHTTEXT',3,'p_highLight_text','run.py',103),
]
